### ISSUE TITLE
"/*" interpreted as comment start even within a string.

### ISSUE THREAD

**Issue by pranjalvachaspati-toast** [nishtahir/language-kotlin#68]
For example, in 

```kotlin

  public fun foo(
    argument1: String = "*/*",
    argument2: Map<String, String> = emptyMap(),
) {}
```

the "/*" in the `argument1` default is treated as the beginning of a comment, and the rest of the code block is treated as a comment.

The Kotlin compiler does not treat it as a comment start, though (see https://pl.kotl.in/d9VnkkShu).

**Comment by steliosfran** [comment]
@nishtahir I was investigating the same issue today but didn't manage to fix it.

For some reason it only happens if this is within a function:
```Kotlin
fun foo(argument: String = "image/*") {}
```
but not a `val`:
```Kotlin
val foo = "image/*"
```

My initial assumption was that the issue is here:
```yaml
patterns:
            -
                include: '#inline'
            -
                begin: '/\*'
```

because the begin clock does not check for double quotes, so I changed it to this `begin: '(?<!")/\*'` but the issue persists.
